# Generated by Django 5.0.3 on 2024-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nato', '0002_nato_delete_article_delete_event_delete_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NATO_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nato',
            name='members',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='NATO',
        ),
    ]
