# Generated by Django 5.0.3 on 2024-03-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nato', '0003_nato_member_remove_nato_members_delete_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nato_member',
            name='photo',
            field=models.ImageField(default=1, upload_to='member_photos/'),
            preserve_default=False,
        ),
    ]
